### ISSUE TITLE
Unexpected generated password when used text does not contain a "." (dot)

### ISSUE THREAD

**Issue by s849** [ghinda/passwordmaker-mobile#1]
Passwords generated from used text that does not contain a "." are inconsistent with other implementations of PasswordMaker.

For example with settings MD5, 8 characters and alphanumeric characters, the output of used text foo.bar (and no password input) is "JX9ivp9G", consistent with the output at http://passwordmaker.org/passwordmaker.html

However, replace the "." in "foo.bar" with a space and passwordmaker-mobile outputs "CmanTHUq" whereas the output at the above URL is "BhQBkzZX".  I also get different results with used text "foobar" so the issue seems to arise whenever a "." is not present in the used text.

The passwordmaker.org website results are consistent will all other implementations of PasswordMaker that I've checked aside from passwordmaker-mobile.  This obviously presents problems when one is using both passwordmaker-mobile and one of the other PasswordMaker implementations.

**Comment by ghinda** [comment]
Thanks for the detailed report! :+1:

I've fixed it and uploaded the new version to the Firefox Marketplace. It's still `Pending Approval`. 
If you're using it on FxOS you'll most probably get an update notification as soon as it's accepted.

**Comment by s849** [comment]
Great, thanks for the excellent app!
